### ISSUE TITLE
Should wrap-session be mentioned?

### ISSUE THREAD

**Issue by SevereOverfl0w** [jamesmacaulay/shopify-clj#9]
With wrap-params now mentioned, I've discovered why I couldn't get any shops to actually show up when auth'd.

The workflow requires/depends upon session, I have no idea if this is a cemerick/friend issue, or a shopify-clj.friend issue, would you be able to shine any light on it @jamesmacaulay?

**Comment by jamesmacaulay** [comment]
Right...the example uses the [compojure.handler/site middleware](https://github.com/weavejester/compojure/blob/1.1.5/src/compojure/handler.clj#L28-L46) (from an old version of compojure). As you can see, that middleware includes `ring.middleware/wrap-session` and others. I'm pretty sure `cemerick/friend` on its own relies on the same stuff, but you're right that it should be better documented.

**Comment by jamesmacaulay** [comment]
I found the relevant bit in the `friend` readme:

[(Note that Friend itself requires some core Ring middlewares: params, keyword-params and nested-params. Most workflows will additionally require session in order to support post-authentication redirection to previously-unauthorized resources, retention of tokens and nonces for workflows like OpenId and oAuth, etc. HTTP Basic is the only provided workflow that does not require session middleware.)](https://github.com/cemerick/friend#authentication)
